
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "app.fullname.nginx" . }}
  labels:
    {{- include "app.labels.nginx" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      name: app
      protocol: TCP
  selector:
    {{- include "app.selectorLabels.nginx" . | nindent 4 }}
