apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cert-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: ebs-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi